fix build break of linux-asus-imx.
ERROR: Trying to resolve runtime dependency kernel-module-imx-gpu-viv resulted in conflicting PREFERRED_PROVIDER entries being found.
The providers found were: ['/source/sources/meta-asus-imx/recipes-kernel/linux/linux-asus-imx_5.15.bb', '/source/sources/meta-imx/meta-bsp/recipes-kernel/linux/linux-imx-mfgtool_5.15.bb']
The PREFERRED_PROVIDER entries resulting in this conflict were: ['PREFERRED_PROVIDER_virtual/kernel = linux-asus-imx', 'PREFERRED_PROVIDER_linux-imx-mfgtool = linux-imx-mfgtool']. You could set PREFERRED_RPROVIDER_kernel-module-imx-gpu-viv
NOTE: Multiple providers are available for runtime kernel-module-imx-gpu-viv (linux-imx-mfgtool, linux-asus-imx, kernel-module-imx-gpu-viv, linux-fslc-lts-mfgtool, linux-fslc-mfgtool)
Consider defining a PREFERRED_RPROVIDER entry to match kernel-module-imx-gpu-viv
NOTE: Runtime target 'kernel-module-imx-gpu-viv' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['kernel-module-imx-gpu-viv']
NOTE: Runtime target 'weston-xwayland' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['weston-xwayland', 'virtual/libgles2', 'kernel-module-imx-gpu-viv']
ERROR: Required build target 'imx-image-full' has no buildable providers.
Missing or unbuildable dependency chain was: ['imx-image-full', 'weston-xwayland', 'virtual/libgles2', 'kernel-module-imx-gpu-viv']

Change-Id: I6aba169ee15f81bf83ba1ea576129a090a592a25